apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx

---

apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: nginx