apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{.Values.cronjob1.name}}
spec:
  schedule: "*/5 * * * *"  # Runs every 5 minutes. You can adjust the schedule as needed.
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{.Values.cronjob1.containerName}}
            image: {{.Values.cronjob1.image}}  # Replace with an image that 
            command:
              - "/bin/sh"
              - "-c"
              - |
                echo "Random String: $(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 10)"
                echo "Pod Name: $(hostname)"
          restartPolicy: {{.Values.cronjob1.restartPolicy}}

