apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service1.name }}
spec:
  ports:
  - port: {{ .Values.service1.port }}
    protocol: {{ .Values.service1.protocol }}
    targetPort: {{ .Values.service1.targetPort }}
  selector:
    app: {{ .Values.service1.selector }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service2.name }}
spec:
  ports:
  - port: {{ .Values.service2.port }}
    protocol: {{ .Values.service2.protocol }}
    targetPort: {{ .Values.service2.targetPort }}
  type: {{ .Values.service2.type }}
  selector:
    app: {{ .Values.service1.selector }}

