name: first deploy helm chart 

on: workflow_dispatch

env:
  aws_region: us-east-2
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 3.13.0 
      - name: Run Helm Lint
        run: helm lint .

  template:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 3.13.0 

      - name: Run Helm Template
        run: helm template .


  deploy:
    needs: template
    runs-on: ubuntu-latest
    env:
      aws_region: us-east-2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 3.13.0 

      - name: install kubectl
        uses: azure/setup-kubectl@v3
        id: install
        
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: connect to the cluster
        run: |
          aws s3 ls
          aws eks update-kubeconfig --region us-east-2 --name my-eks-cluster
          cat /home/runner/.kube/config
          kubectl get pods
          
      - name: Run Helm 
        run: helm upgrade my-chart --install  . --kubeconfig /home/runner/.kube/config
